version: '3'

services:
  peer:
    image: "dfherr/dejima-prototype:latest"
    requires:
      - "postgres"
    networks: ["peer-net"]
    environment:
      - "RAILS_ENV=peer_development"
      - "PEER_TYPE=government"
      - "PEER_NETWORK_ADDRESS=peer.dejima-swarm-network"
      - "DEJIMA_PEER_DATABASE_HOST=postgres.peer-net"
  postgres:
    image: "dfherr/dejima-postgres:latest"
    networks: ["peer-net"]
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=foobar"
      - "DEJIMA_API_ENDPOINT=peer.peer-net:3000/dejima/propagate"
networks:
  peer-net: