version: '3'

services:
  peer-bank:
    image: "dfherr/dejima-prototype:latest"
    networks: ["dejima-swarm-network"]
    environment:
      - "RAILS_ENV=peer_development"
      - "DEJIMA_PEER_DATABASE_HOST=172.17.0.1"
      - "PEER_TYPE=bank"
      - "PEER_NETWORK_ADDRESS=dejima-peer-bank.dejima-swarm-network"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==dejima-peer-bank]
  peer-gov:
    image: "dfherr/dejima-prototype:latest"
    networks: ["dejima-swarm-network"]
    environment:
      - "RAILS_ENV=peer_development"
      - "DEJIMA_PEER_DATABASE_HOST=172.17.0.1"
      - "PEER_TYPE=government"
      - "PEER_NETWORK_ADDRESS=dejima-peer-gov.dejima-swarm-network"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==dejima-peer-gov]
networks:
  dejima-swarm-network:
    external: true