version: '3'

services:
  peer:
    image: "dfherr/dejima-prototype:latest"
    networks: ["dejima-swarm-network", "peer-net"]
    environment:
      - "RAILS_ENV=peer_development"
      - "PEER_TYPE=government"
      - "PEER_NETWORK_ADDRESS=peer.dejima-swarm-network"
      - "DEJIMA_PEER_DATABASE_HOST=postgres.peer-net"
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname==dejima-peer1-h4t4]
networks:
  dejima-swarm-network:
    external: true
  peer-net: