version: '3'

services:
  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - dejima-swarm-network
  logspout:
    image: dfherr/logspout-logstash:latest
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 20
        window: 60s
    environment:
      - "DOCKER_LABELS=true"
      - "ROUTE_URIS=logstash+tcp://elk:5044"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    networks:
      - dejima-swarm-network
networks:
   dejima-swarm-network:
    external: true
