version: '3'

services:
  elk:
    image: sebp/elk:latest
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - "/home/ubuntu/02-beats-input.conf:/etc/logstash/conf.d/02-beats-input.conf"
      - "/home/ubuntu/30-output.conf:/etc/logstash/conf.d/30-output.conf"
    deploy:
      placement:
        constraints: [node.role==manager]
    networks:
      - dejima-swarm-network
  logspout:
    image: dfherr/logspout-logstash:latest
    deploy:
      mode: global
      placement:
        constraints: [node.role!=manager]
      restart_policy:
        condition: any
        delay: 15s
        max_attempts: 20
        window: 60s
    environment:
      - "DOCKER_LABELS=true"
      - "DECODE_JSON_LOGS=false"
      - "ROUTE_URIS=logstash+udp://elk:5044"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dejima-swarm-network
networks:
   dejima-swarm-network:
    external: true