default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DEJIMA_PEER_DATABASE_HOST'] || 'localhost' %>
  port: <%= (ENV['DEJIMA_PEER_DATABASE_PORT'] || 5432).to_i %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>

development: &development
  <<: *default
  database: dejima_peer_dev

test: &test
  <<: *default
  database: dejima_peer_test

production: &production
  <<: *default
  database: dejima_peer_prod
  # better way to set production pw
  # password: <%= ENV['DEJIMA_PEER_DATABASE_PASSWORD'] %> 

client_development:
  <<: *development
  username: postgres
  password: foobar

client_test:
  <<: *test
  username: postgres
  password: foobar

client_production:
  <<: *production
  username: postgres

peer_development:
  <<: *development
  username: dejima
  password: barfoo

peer_test:
  <<: *test
  username: dejima
  password: barfoo

peer_production:
  <<: *production
  username: dejima
  password: barfoo